-- MySQL Script generated by MySQL Workbench
-- 12/27/15 18:38:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema euskallovers
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `euskallovers` ;

-- -----------------------------------------------------
-- Schema euskallovers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `euskallovers` DEFAULT CHARACTER SET utf8 ;
USE `euskallovers` ;

-- -----------------------------------------------------
-- Table `euskallovers`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `euskallovers`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `euskallovers`.`Usuario` (
  `Nick` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  `Genero` TINYINT(1) NOT NULL,
  `Edad` INT NOT NULL,
  `Altura` FLOAT NULL,
  `Peso` INT NULL,
  `Constitucion` VARCHAR(15) NOT NULL,
  `Ciudad` VARCHAR(25) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Foto` VARCHAR(125) NOT NULL,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  PRIMARY KEY (`Nick`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `euskallovers`.`Aficion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `euskallovers`.`Aficion` ;

CREATE TABLE IF NOT EXISTS `euskallovers`.`Aficion` (
  `Nombre` VARCHAR(15) NOT NULL,
  `Nick` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nombre`, `Nick`),
  INDEX `fk_Aficion_Usuario1_idx` (`Nick` ASC),
  CONSTRAINT `fk_Aficion_Usuario1`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`Usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `euskallovers`.`Personalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `euskallovers`.`Personalidad` ;

CREATE TABLE IF NOT EXISTS `euskallovers`.`Personalidad` (
  `Nick` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nick`, `Nombre`),
  CONSTRAINT `NickForeignUser`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`Usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `euskallovers`.`Interes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `euskallovers`.`Interes` ;

CREATE TABLE IF NOT EXISTS `euskallovers`.`Interes` (
  `Nick` VARCHAR(15) NOT NULL,
  `Genero` TINYINT(1) NOT NULL,
  `Edad` INT NOT NULL,
  `CP` VARCHAR(5) NULL,
  `Peso` INT NULL,
  `Altura` FLOAT NULL,
  `Constitucion` VARCHAR(15) NULL,
  `Ciudad` VARCHAR(25) NULL,
  PRIMARY KEY (`Nick`),
  CONSTRAINT `Nick_fkUser`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`Usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `euskallovers`.`Premium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `euskallovers`.`Premium` ;

CREATE TABLE IF NOT EXISTS `euskallovers`.`Premium` (
  `Nick` VARCHAR(15) NOT NULL,
  `CuentaTarjeta` VARCHAR(15) NULL,
  `Saldo` INT NULL,
  `FechaHora` DATETIME NULL,
  `Pack` INT NULL,
  PRIMARY KEY (`Nick`),
  CONSTRAINT `NickFkUser`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`Usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `euskallovers`.`Visita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `euskallovers`.`Visita` ;

CREATE TABLE IF NOT EXISTS `euskallovers`.`Visita` (
  `Nick1` VARCHAR(15) NOT NULL,
  `Nick2` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick1`, `Nick2`),
  INDEX `nick2_idx` (`Nick2` ASC),
  CONSTRAINT `nick1`
    FOREIGN KEY (`Nick1`)
    REFERENCES `euskallovers`.`Usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nick2`
    FOREIGN KEY (`Nick2`)
    REFERENCES `euskallovers`.`Usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `euskallovers`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `euskallovers`;
INSERT INTO `euskallovers`.`Usuario` (`Nick`, `Email`, `Password`, `Genero`, `Edad`, `Altura`, `Peso`, `Constitucion`, `Ciudad`, `CP`, `Foto`) VALUES ('AsierLO', 'asierlo@asier.com', 'asier', 1, 24, 1.70, 70, 'Musculoso', 'Bilbao', '01013', 'lalala');
INSERT INTO `euskallovers`.`Usuario` (`Nick`, `Email`, `Password`, `Genero`, `Edad`, `Altura`, `Peso`, `Constitucion`, `Ciudad`, `CP`, `Foto`) VALUES ('AsierRO', 'asierro@asier.com', 'asier', 0, 20, 1.80, 75, 'Delgado', 'Vitoria-Gasteiz', '01012', 'lalala');
INSERT INTO `euskallovers`.`Usuario` (`Nick`, `Email`, `Password`, `Genero`, `Edad`, `Altura`, `Peso`, `Constitucion`, `Ciudad`, `CP`, `Foto`) VALUES ('Adrián', 'adrian@adrian.com', 'adrian', 67, 20, 1.70, 70, 'Fornido', 'San Sebastian', '01010', 'lalala');

COMMIT;


-- -----------------------------------------------------
-- Data for table `euskallovers`.`Aficion`
-- -----------------------------------------------------
START TRANSACTION;
USE `euskallovers`;
INSERT INTO `euskallovers`.`Aficion` (`Nombre`, `Nick`) VALUES ('Lectura', 'AsierLO');
INSERT INTO `euskallovers`.`Aficion` (`Nombre`, `Nick`) VALUES ('Tecnologia', 'AsierLO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `euskallovers`.`Personalidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `euskallovers`;
INSERT INTO `euskallovers`.`Personalidad` (`Nick`, `Nombre`) VALUES ('Alegre', 'AsierLO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `euskallovers`.`Interes`
-- -----------------------------------------------------
START TRANSACTION;
USE `euskallovers`;
INSERT INTO `euskallovers`.`Interes` (`Nick`, `Genero`, `Edad`, `CP`, `Peso`, `Altura`, `Constitucion`, `Ciudad`) VALUES ('AsierLO', 0, 43, '01321', 50, 1.69, 'Fornido', 'Bilbao');
INSERT INTO `euskallovers`.`Interes` (`Nick`, `Genero`, `Edad`, `CP`, `Peso`, `Altura`, `Constitucion`, `Ciudad`) VALUES ('AsierRO', 1, 54, NULL, NULL, NULL, NULL, NULL);

COMMIT;

