-- MySQL Script generated by MySQL Workbench
-- 01/03/16 13:53:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema euskallovers
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `euskallovers` ;

-- -----------------------------------------------------
-- Schema euskallovers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `euskallovers` DEFAULT CHARACTER SET utf8 ;
USE `euskallovers` ;

-- -----------------------------------------------------
-- Table `euskallovers`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskallovers`.`usuario` (
  `Nick` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(25) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  `Genero` TINYINT(1) NOT NULL,
  `Edad` INT(11) NOT NULL,
  `Altura` FLOAT NULL DEFAULT NULL,
  `Peso` INT(11) NULL DEFAULT NULL,
  `Constitucion` VARCHAR(15) NOT NULL,
  `Ciudad` VARCHAR(25) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Foto` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`Nick`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euskallovers`.`aficion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskallovers`.`aficion` (
  `Nombre` VARCHAR(15) NOT NULL,
  `Nick` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nombre`, `Nick`),
  INDEX `fk_Aficion_Usuario1_idx` (`Nick` ASC),
  CONSTRAINT `fk_Aficion_Usuario1`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euskallovers`.`interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskallovers`.`interes` (
  `Nick` VARCHAR(15) NOT NULL,
  `Genero` TINYINT(1) NOT NULL,
  `Edad` INT(11) NOT NULL,
  `CP` VARCHAR(5) NULL DEFAULT NULL,
  `Peso` INT(11) NULL DEFAULT NULL,
  `Altura` FLOAT NULL DEFAULT NULL,
  `Constitucion` VARCHAR(15) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`Nick`),
  CONSTRAINT `Nick_fkUser`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euskallovers`.`personalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskallovers`.`personalidad` (
  `Nick` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nick`, `Nombre`),
  CONSTRAINT `NickForeignUser`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euskallovers`.`premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskallovers`.`premium` (
  `Nick` VARCHAR(15) NOT NULL,
  `CuentaTarjeta` VARCHAR(18) NOT NULL,
  `Saldo` INT(11) NOT NULL,
  `FechaHora` DATETIME NOT NULL,
  `Pack` INT(11) NOT NULL,
  PRIMARY KEY (`Nick`),
  CONSTRAINT `NickFkUser`
    FOREIGN KEY (`Nick`)
    REFERENCES `euskallovers`.`usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euskallovers`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euskallovers`.`visita` (
  `Nick1` VARCHAR(15) NOT NULL,
  `Nick2` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Nick1`, `Nick2`),
  INDEX `nick2_idx` (`Nick2` ASC),
  CONSTRAINT `nick1`
    FOREIGN KEY (`Nick1`)
    REFERENCES `euskallovers`.`usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nick2`
    FOREIGN KEY (`Nick2`)
    REFERENCES `euskallovers`.`usuario` (`Nick`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
